# Generated by Django 3.2.4 on 2021-08-30 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'verbose_name_plural': 'FAQ Categories'},
        ),
        migrations.AlterModelOptions(
            name='faqentry',
            options={'verbose_name_plural': 'FAQ Entries'},
        ),
        migrations.AlterModelOptions(
            name='faqquestion',
            options={'verbose_name_plural': 'FAQ Questions'},
        ),
        migrations.AlterModelTable(
            name='faqcategory',
            table='FaqCategory',
        ),
        migrations.AlterModelTable(
            name='faqentry',
            table='FaqEntry',
        ),
        migrations.AlterModelTable(
            name='faqquestion',
            table='FaqQuestion',
        ),
    ]
