# Generated by Django 3.2.4 on 2021-07-07 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqcategory',
            name='friendly_name',
        ),
    ]
