# Generated by Django 3.2.4 on 2021-07-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_auto_20210707_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqentry',
            name='clickCount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
