# Generated by Django 3.2.4 on 2021-07-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0006_auto_20210718_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqquestion',
            old_name='title',
            new_name='question',
        ),
    ]
