# Generated by Django 3.2.4 on 2021-07-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0007_rename_title_faqquestion_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqquestion',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
