# Generated by Django 3.2.4 on 2021-06-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
