# Generated by Django 3.2.4 on 2021-06-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210622_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_companion',
            field=models.BooleanField(default=False, verbose_name='IS_COMPANION'),
        ),
    ]
