# Generated by Django 3.2.4 on 2021-06-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20210623_1418'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
