# Generated by Django 3.2.4 on 2021-06-24 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0016_delete_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='MondayAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_9am', models.BooleanField(default=False)),
                ('hour_10am', models.BooleanField(default=False)),
                ('hour_11am', models.BooleanField(default=False)),
                ('hour_12pm', models.BooleanField(default=False)),
                ('hour_1pm', models.BooleanField(default=False)),
                ('hour_2pm', models.BooleanField(default=False)),
                ('hour_3pm', models.BooleanField(default=False)),
                ('hour_4pm', models.BooleanField(default=False)),
                ('hour_5pm', models.BooleanField(default=False)),
                ('hour_6pm', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_teacher', models.BooleanField(default=False)),
                ('monday_available', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.mondayavailable')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
