# Generated by Django 3.2.4 on 2021-06-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_mondayavailable_teacherprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='monday_available',
        ),
    ]
