# Generated by Django 3.2.4 on 2021-06-24 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_remove_teacherprofile_monday_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mondayavailable',
            name='user',
        ),
        migrations.AddField(
            model_name='mondayavailable',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.teacherprofile'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='monday_available',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.mondayavailable'),
        ),
    ]
