# Generated by Django 3.2.4 on 2021-06-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20210624_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='is_teacher',
            new_name='friday_available',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='friday_available',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='monday_available',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='thursday_available',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tuesday_available',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='wednesday_available',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='is_companion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='thursday_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='tuesday_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='wednesday_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='monday_available',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='MondayAvailable',
        ),
    ]
