# Generated by Django 3.2.4 on 2021-06-25 12:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0020_auto_20210625_1200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherProfile',
            new_name='CompanionProfile',
        ),
    ]
