# Generated by Django 3.2.4 on 2021-06-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_rename_teacherprofile_companionprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companionprofile',
            name='is_companion',
        ),
    ]
