# Generated by Django 3.2.4 on 2021-06-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_remove_companionprofile_is_companion'),
    ]

    operations = [
        migrations.AddField(
            model_name='companionprofile',
            name='code_review_offered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companionprofile',
            name='deployment_assist_offered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companionprofile',
            name='interview_prep_offered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companionprofile',
            name='peer_programming_offered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companionprofile',
            name='troubleshooting_offered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companionprofile',
            name='whiteboarding_offered',
            field=models.BooleanField(default=False),
        ),
    ]
