# Generated by Django 3.2.4 on 2021-06-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_auto_20210625_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companionprofile',
            old_name='whiteboarding_offered',
            new_name='whiteboarding_session_offered',
        ),
    ]
