# Generated by Django 3.2.4 on 2021-08-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_rename_whiteboarding_offered_companionprofile_whiteboarding_session_offered'),
    ]

    operations = [
        migrations.AddField(
            model_name='companionprofile',
            name='bio',
            field=models.TextField(default=False),
        ),
    ]
