# Generated by Django 3.2.4 on 2021-08-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_companionprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companionprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
