# Generated by Django 3.2.4 on 2021-08-18 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_alter_companionprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companionprofile',
            name='code_review_offered',
        ),
        migrations.RemoveField(
            model_name='companionprofile',
            name='deployment_assist_offered',
        ),
        migrations.RemoveField(
            model_name='companionprofile',
            name='interview_prep_offered',
        ),
        migrations.RemoveField(
            model_name='companionprofile',
            name='peer_programming_offered',
        ),
        migrations.RemoveField(
            model_name='companionprofile',
            name='troubleshooting_offered',
        ),
        migrations.RemoveField(
            model_name='companionprofile',
            name='whiteboarding_session_offered',
        ),
    ]
