# Generated by Django 3.2.4 on 2021-08-25 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('icon', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(max_length=254, null=True)),
                ('description', models.CharField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('bullet_point_1', models.CharField(blank=True, max_length=254, null=True)),
                ('bullet_point_2', models.CharField(blank=True, max_length=254, null=True)),
                ('bullet_point_3', models.CharField(blank=True, max_length=254, null=True)),
                ('bullet_point_4', models.CharField(blank=True, max_length=254, null=True)),
                ('companion', models.ManyToManyField(to='profiles.CompanionProfile')),
                ('price_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.pricetype')),
            ],
        ),
    ]
