# Generated by Django 3.2.4 on 2021-06-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.CharField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_type', models.CharField(max_length=254)),
                ('bullet_point_1', models.CharField(blank=True, max_length=254, null=True)),
                ('bullet_point_2', models.CharField(blank=True, max_length=254, null=True)),
                ('bullet_point_3', models.CharField(blank=True, max_length=254, null=True)),
                ('bullet_point_4', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
