# Generated by Django 3.2.4 on 2021-08-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('services', '0002_alter_service_companion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='companion',
            field=models.ManyToManyField(blank=True, to='profiles.CompanionProfile'),
        ),
    ]
