# Generated by Django 3.2.4 on 2021-06-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='endpoint',
            field=models.CharField(default='#', max_length=254),
        ),
    ]
