# Generated by Django 3.2.4 on 2021-06-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_endpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='id',
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
