# Generated by Django 3.2.4 on 2021-07-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20210616_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
