# Generated by Django 3.2.4 on 2021-08-16 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_alter_companionprofile_bio'),
        ('services', '0006_service_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='companion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.companionprofile'),
        ),
    ]
