# Generated by Django 3.2.4 on 2021-08-16 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_service_companion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='companion',
        ),
    ]
