# Generated by Django 3.2.4 on 2021-06-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='companion',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='companion_selected',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='day_selected',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
