# Generated by Django 3.2.4 on 2021-07-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20210720_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='end_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='start_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
