# Generated by Django 3.2.4 on 2021-07-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20210720_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='day_selected',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='end_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='start_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
