# Generated by Django 3.2.4 on 2021-06-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210615_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='endpoint',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
